0_poison_pattern:
- - 0
  - 0
- - 0
  - 1
- - 0
  - 2
- - 0
  - 3
- - 0
  - 6
- - 0
  - 7
- - 0
  - 8
- - 0
  - 9
- - 3
  - 0
- - 3
  - 1
- - 3
  - 2
- - 3
  - 3
- - 3
  - 6
- - 3
  - 7
- - 3
  - 8
- - 3
  - 9
algorithm: FedAvg
batch_size: 128
decay: 0.0005
defence_method: ours
dirichlet_alpha: 1
epochs: 2
eta: 1
is_poison: true
local_epochs: 2
lr: 0.01
lr_decay: true
lr_decay_epoch: 1
lr_decay_gamma: 0.998
model: r8
momentum: 0.9
num_clients: 10
number_of_total_participants: 100
ours_standard:
- 0.5
- 0.4
- 0.3
- 0.2
poison_client_num: 10
poison_epochs: 6
poison_lr: 0.005
poison_rate: 0.5
reward_pool: 0.0
sampling_dirichlet: true
seed: 1
task_id: '5'
task_name: '5'
trigger_num: 1
type: CIFAR10
