# Generated by Django 6.0 on 2026-01-05 07:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="账户余额",
                    ),
                ),
                (
                    "virtual_coins",
                    models.IntegerField(default=100, verbose_name="虚拟币"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DataBlock",
            fields=[
                (
                    "block_id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="数据块ID",
                    ),
                ),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[("CIFAR10", "CIFAR-10"), ("MNIST", "MNIST")],
                        default="CIFAR10",
                        max_length=20,
                        verbose_name="数据集类型",
                    ),
                ),
                (
                    "data_size",
                    models.IntegerField(default=0, verbose_name="数据样本数量"),
                ),
                (
                    "base_price",
                    models.IntegerField(default=10, verbose_name="基础价格(虚拟币)"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可购买"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "current_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_blocks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="当前拥有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据块",
                "verbose_name_plural": "数据块",
                "ordering": ["block_id"],
            },
        ),
        migrations.CreateModel(
            name="DataBlockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "购买"),
                            ("sell", "出售"),
                            ("gift", "赠送"),
                        ],
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="交易价格(虚拟币)")),
                ("coins_before", models.IntegerField(verbose_name="交易前虚拟币")),
                ("coins_after", models.IntegerField(verbose_name="交易后虚拟币")),
                ("description", models.TextField(blank=True, verbose_name="交易描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="交易时间"),
                ),
                (
                    "data_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="federation_app.datablock",
                        verbose_name="数据块",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datablock_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据块交易记录",
                "verbose_name_plural": "数据块交易记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FederationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="任务编号"
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=100, verbose_name="任务名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("paused", "已暂停"),
                            ("stopped", "已停止"),
                            ("completed", "已完成"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "current_epoch",
                    models.IntegerField(default=0, verbose_name="当前轮次"),
                ),
                (
                    "total_epochs",
                    models.IntegerField(default=100, verbose_name="总轮次"),
                ),
                (
                    "active_users",
                    models.IntegerField(default=0, verbose_name="活跃用户数"),
                ),
                (
                    "model_architecture",
                    models.CharField(
                        choices=[
                            ("CNN", "CNN"),
                            ("r8", "ResNet8"),
                            ("r18", "ResNet18"),
                            ("r34", "ResNet34"),
                        ],
                        default="r8",
                        max_length=20,
                        verbose_name="模型结构",
                    ),
                ),
                (
                    "dataset",
                    models.CharField(
                        choices=[("MNIST", "MNIST"), ("CIFAR10", "CIFAR10")],
                        default="CIFAR10",
                        max_length=20,
                        verbose_name="数据集",
                    ),
                ),
                ("epochs", models.IntegerField(default=2000, verbose_name="训练轮数")),
                (
                    "reward_pool",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="奖金池",
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("reward", "奖金池模式"),
                            ("shareholding", "股份制模式"),
                        ],
                        default="shareholding",
                        max_length=20,
                        verbose_name="支付模式",
                    ),
                ),
                (
                    "model_status",
                    models.CharField(
                        choices=[
                            ("training", "训练中"),
                            ("online", "已上线"),
                            ("offline", "已下线"),
                        ],
                        default="training",
                        max_length=20,
                        verbose_name="模型状态",
                    ),
                ),
                (
                    "usage_fee_per_request",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        max_digits=10,
                        verbose_name="单次使用费",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="累计收益",
                    ),
                ),
                (
                    "total_usage_count",
                    models.IntegerField(default=0, verbose_name="累计使用次数"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "联邦学习任务",
                "verbose_name_plural": "联邦学习任务",
            },
        ),
        migrations.CreateModel(
            name="ModelUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="使用费用"
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        default="prediction", max_length=20, verbose_name="使用类型"
                    ),
                ),
                (
                    "input_data_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="输入数据哈希"
                    ),
                ),
                (
                    "prediction_result",
                    models.TextField(blank=True, verbose_name="预测结果"),
                ),
                (
                    "used_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="使用时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="federation_app.federationtask",
                        verbose_name="联邦任务",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_usages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型使用记录",
                "verbose_name_plural": "模型使用记录",
                "ordering": ["-used_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revenue_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="收益金额"
                    ),
                ),
                (
                    "share_ratio_snapshot",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="股份占比快照"
                    ),
                ),
                (
                    "distributed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                (
                    "shareholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="股东",
                    ),
                ),
                (
                    "source_usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="federation_app.modelusagerecord",
                        verbose_name="来源使用记录",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_distributions",
                        to="federation_app.federationtask",
                        verbose_name="联邦任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "收益分配记录",
                "verbose_name_plural": "收益分配记录",
                "ordering": ["-distributed_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("error", "错误"),
                            ("success", "成功"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="日志级别",
                    ),
                ),
                ("message", models.TextField(verbose_name="日志内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="federation_app.federationtask",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务日志",
                "verbose_name_plural": "任务日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("recharge", "充值"),
                            ("withdraw", "提现"),
                            ("model_usage", "模型使用"),
                            ("revenue", "收益分配"),
                            ("share_trade", "股份交易"),
                            ("data_purchase", "数据购买"),
                            ("reward_distribution", "奖金分配"),
                        ],
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易金额"
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易前余额"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易后余额"
                    ),
                ),
                ("description", models.TextField(verbose_name="交易描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "related_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="federation_app.federationtask",
                        verbose_name="关联任务",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "交易记录",
                "verbose_name_plural": "交易记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("data", "数据块"),
                            ("model_share", "模型股份"),
                            ("virtual_coin", "虚拟币"),
                        ],
                        max_length=20,
                        verbose_name="资产类型",
                    ),
                ),
                (
                    "asset_reference",
                    models.CharField(max_length=100, verbose_name="资产引用ID"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="数量"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资产",
                "verbose_name_plural": "用户资产",
            },
        ),
        migrations.CreateModel(
            name="GlobalAccuracy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epoch", models.IntegerField(verbose_name="训练轮次")),
                ("accuracy", models.FloatField(verbose_name="全局准确度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_accuracies",
                        to="federation_app.federationtask",
                        verbose_name="联邦任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "全局准确度记录",
                "verbose_name_plural": "全局准确度记录",
                "ordering": ["epoch"],
                "unique_together": {("task", "epoch")},
            },
        ),
        migrations.CreateModel(
            name="ModelShareholding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_ratio",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="股份占比"
                    ),
                ),
                (
                    "initial_contribution",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="初始贡献度"
                    ),
                ),
                (
                    "tradable",
                    models.BooleanField(default=True, verbose_name="是否可交易"),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="获得时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareholdings",
                        to="federation_app.federationtask",
                        verbose_name="联邦任务",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareholdings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型股份持有记录",
                "verbose_name_plural": "模型股份持有记录",
                "unique_together": {("task", "user")},
            },
        ),
        migrations.CreateModel(
            name="RewardDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution_ratio",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="贡献占比"
                    ),
                ),
                (
                    "reward_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="奖金金额"
                    ),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="是否已支付")),
                (
                    "distributed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_distributions",
                        to="federation_app.federationtask",
                        verbose_name="联邦任务",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "奖金分配记录",
                "verbose_name_plural": "奖金分配记录",
                "unique_together": {("task", "user")},
            },
        ),
        migrations.CreateModel(
            name="TaskParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="federation_app.federationtask",
                        verbose_name="联邦任务",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务参与者",
                "verbose_name_plural": "任务参与者",
                "unique_together": {("task", "user")},
            },
        ),
        migrations.CreateModel(
            name="UserDataBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquisition_type",
                    models.CharField(
                        choices=[
                            ("free", "免费赠送"),
                            ("purchased", "购买获得"),
                            ("rewarded", "奖励获得"),
                        ],
                        default="purchased",
                        max_length=20,
                        verbose_name="获得方式",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="获得时间"),
                ),
                (
                    "data_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_records",
                        to="federation_app.datablock",
                        verbose_name="数据块",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_blocks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户数据块持有记录",
                "verbose_name_plural": "用户数据块持有记录",
                "ordering": ["-acquired_at"],
                "unique_together": {("user", "data_block")},
            },
        ),
    ]
