# Generated by Django 5.2.8 on 2025-11-28 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataBlock",
            fields=[
                (
                    "block_id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="数据块ID",
                    ),
                ),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[("CIFAR10", "CIFAR-10"), ("MNIST", "MNIST")],
                        default="CIFAR10",
                        max_length=20,
                        verbose_name="数据集类型",
                    ),
                ),
                ("data_size", models.IntegerField(default=0, verbose_name="数据样本数量")),
                (
                    "base_price",
                    models.IntegerField(default=10, verbose_name="基础价格(虚拟币)"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可购买"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "current_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_blocks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="当前拥有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据块",
                "verbose_name_plural": "数据块",
                "ordering": ["block_id"],
            },
        ),
        migrations.CreateModel(
            name="DataBlockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("purchase", "购买"), ("sell", "出售"), ("gift", "赠送")],
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="交易价格(虚拟币)")),
                ("coins_before", models.IntegerField(verbose_name="交易前虚拟币")),
                ("coins_after", models.IntegerField(verbose_name="交易后虚拟币")),
                ("description", models.TextField(blank=True, verbose_name="交易描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="交易时间"),
                ),
                (
                    "data_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="federation_app.datablock",
                        verbose_name="数据块",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datablock_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据块交易记录",
                "verbose_name_plural": "数据块交易记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserDataBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquisition_type",
                    models.CharField(
                        choices=[
                            ("free", "免费赠送"),
                            ("purchased", "购买获得"),
                            ("rewarded", "奖励获得"),
                        ],
                        default="purchased",
                        max_length=20,
                        verbose_name="获得方式",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="获得时间"),
                ),
                (
                    "data_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_records",
                        to="federation_app.datablock",
                        verbose_name="数据块",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_blocks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户数据块持有记录",
                "verbose_name_plural": "用户数据块持有记录",
                "ordering": ["-acquired_at"],
                "unique_together": {("user", "data_block")},
            },
        ),
    ]
