# Generated by Django 6.0 on 2026-01-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("federation_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ganache_index",
            field=models.IntegerField(
                blank=True,
                help_text="对应Ganache中的账户索引(0-9)",
                null=True,
                unique=True,
                verbose_name="Ganache账户索引",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="账户余额(已废弃)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="virtual_coins",
            field=models.IntegerField(default=0, verbose_name="虚拟币(已废弃)"),
        ),
    ]
